backend:
  image:
    repository: url-shortener-backend
    tag: "dev"
    pullPolicy: IfNotPresent
  replicas: 2
  databaseSecret: backend-db
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
frontend:
  image:
    repository: url-shortener-frontend
    tag: "dev"
    pullPolicy: IfNotPresent
  replicas: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"