apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: url-shortener
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: url-shortener-backend:dev
          imagePullPolicy: IfNotPresent
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: backend-db
          securityContext:
            runAsNonRoot: true